### ISSUE TITLE
"Overview of Tools Supporting Planning for Automated Driving"

### ISSUE THREAD

**Issue by KailinTong** [chauvinSimon/My_Bibliography_for_Research_on_Autonomous_Driving#1]
Hello Simon,

thank you for sharing after reading "Overview of Tools Supporting Planning for Automated Driving". I really like the way you summarize papers. Good Job!

A small typo is INTERACTION dataset was surveyed in "Overview of Tools Supporting Planning for Automated Driving" when you look at the table.

br
Kailin

**Comment by chauvinSimon** [comment]
Hi Kailin,
I am so sorry I missed your message.
Thank you for your feedback!

Cheers
Simon
